# ----------------------------------------------------------------------------------------------------------------------
# PRIMARY SETTINGS
[tool.poetry]
name = "bacon"
version = "0.1.0"
description = "CLI client to Bacon Ipsum public API."
authors = ["Jesse Butcher <boweeb@gmail.com>"]
license = "MIT"

keywords = ["bacon", "http", "api", "lorem", "ipsum"]

homepage = "https://github.com/boweeb/bacon"
repository = "git@github.com:boweeb/bacon.git"
documentation = "file://./README.md"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
]

[tool.poetry.scripts]
bacon = 'bacon.cli.entry:main'


# ----------------------------------------------------------------------------------------------------------------------
# DEPENDENCIES
[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
click = "^7.1.2"            # CLI framework
click-aliases = "^1.0.1"    # Extends Click with command aliases
colorama = "^0.4.4"         # ASCII color lib -- still needed?
rich = "^9.0.1"             # ASCII decorator
alive-progress = "^1.6.1"   # Progress bars
cerberus = "^1.3.2"         # Schema validation

[tool.poetry.dev-dependencies]
ipython = "*"               # Alternative REPL
bpython = "*"               # Alternative REPL
coverage = "*"              # Code coverage report
pytest = "*"                # Test suite framework
pytest-runner = "*"         # Test suite runner
pytest-cov = "*"            # Integrate coverage with tests
pytest-bdd = "*"            # Gherkin support for pytest
#pdoc3 = "*"                 # API documentation generator
#tox = "*"                   # Test environment management
#pylama = "*"                # Linting suite
#Sphinx = "*"                # Project documentation generator
flake8 = "*"


# ----------------------------------------------------------------------------------------------------------------------
# TOOLS
black = "^20.8b1"
[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
atomic = true
lines_after_imports = 2
lines_between_types = 0

# Configure custom sections
#   Reference: default for "sections" = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_aws = ["boto3", "botocore"]
known_click = ["click"]
sections = ["FUTURE", "STDLIB", "CLICK", "AWS", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
no_lines_before = ["AWS", "THIRDPARTY"]


# ----------------------------------------------------------------------------------------------------------------------
# FIN
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
